In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
np.version.version

'1.23.5'

In [3]:
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [5]:
a3 = np.empty([2,5])
print(a3)

[[4.24399158e-314 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]]


In [6]:
a4 = np.zeros((2,7))
print (a4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
a5 = np.full ((2,3),1.5)
print(a5)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [8]:
a6 = np.identity(8)
print (a6)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
a7 = np.arange(2,14, 3)
print(a7)

[ 2  5  8 11]


In [13]:
a8 = np.linspace(0, 10, 5)
print (a8)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
a9 = np.linspace(0, 10, 4)
print (a9)

[ 0.          3.33333333  6.66666667 10.        ]


In [15]:
a5.ndim

2

In [16]:
a5.shape

(2, 3)

In [17]:
a5.size

6

In [18]:
a10 = np.full ((2,3),"a")
print (a10)
a10.size

[['a' 'a' 'a']
 ['a' 'a' 'a']]


6

In [19]:
a10.dtype

dtype('<U1')

In [38]:
a7 = np.arange(2,14,3)
print(a7)
print(a7[2])

[ 2  5  8 11]
8


In [28]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)


[[1 2 3]
 [4 5 6]]


In [36]:
a2[1,2]

6

In [49]:
print(a7[:2])


[2 5]


In [50]:
a11 = np.arange(1,10)
print (a11)

[1 2 3 4 5 6 7 8 9]


In [51]:
a11 = np.arange(1,10).reshape(3,3)
print (a11)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
a12 = np.arange(1,13).reshape(4,3)
print (a12)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
print(a11[(a11 %2 == 0)])

[2 4 6 8]


In [59]:
print(a11[(a11 != 5)])

[1 2 3 4 6 7 8 9]
